<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Service\DateService' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/DateService.php';

return $this->services['AppBundle\Service\DateService'] = new \AppBundle\Service\DateService();
