<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFa6mdap\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFa6mdap/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFa6mdap.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFa6mdap\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFa6mdap\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fa6mdap',
    'container.build_id' => '12865050',
    'container.build_time' => 1536061731,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFa6mdap');
